# Generated by Django 6.0.2 on 2026-03-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
                ('OSGrid', models.CharField(max_length=2)),
                ('OSEasting', models.IntegerField()),
                ('OSNorthing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoleCount', models.IntegerField()),
                ('IsOnPrivateLand', models.BooleanField()),
                ('RockCannonID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forms.position')),
            ],
        ),
        migrations.CreateModel(
            name='RCName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('LangTag', models.CharField(max_length=2)),
                ('RockCannonID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forms.position')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Story', models.TextField()),
                ('LangTag', models.CharField(max_length=2)),
                ('RockCannonID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='forms.position')),
            ],
        ),
    ]
