# Generated by Django 6.0.2 on 2026-03-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RockCannon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rock Cannon',
                'verbose_name_plural': 'Rock Cannons',
            },
        ),
        migrations.CreateModel(
            name='RCName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('rock_cannon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='forms.rockcannon')),
            ],
            options={
                'verbose_name': 'RC Name',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('os_grid', models.CharField(blank=True, max_length=3, null=True)),
                ('os_easting', models.IntegerField(blank=True, null=True)),
                ('os_northing', models.IntegerField(blank=True, null=True)),
                ('rock_cannon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='forms.rockcannon')),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_count', models.IntegerField(blank=True, null=True)),
                ('is_on_private_land', models.BooleanField(default=False)),
                ('rock_cannon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='forms.rockcannon')),
            ],
            options={
                'verbose_name': 'Metadata',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('rock_cannon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='forms.rockcannon')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
