# Generated by Django 6.0.2 on 2026-03-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockcannon',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
