# Generated by Django 6.0.2 on 2026-03-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rockcannon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='language',
        ),
        migrations.AddField(
            model_name='rockcannon',
            name='slug_cy',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rockcannon',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='story_text_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='story_text_en',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='RCName',
        ),
    ]
