# Generated by Django 6.0.2 on 2026-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_story_language_rockcannon_slug_cy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockcannon',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
