# Generated by Django 6.0.2 on 2026-03-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rockcannon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockcannon',
            name='slug_cy',
        ),
        migrations.RemoveField(
            model_name='rockcannon',
            name='slug_en',
        ),
        migrations.AddField(
            model_name='rockcannon',
            name='name_cy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rockcannon',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
