# Generated by Django 6.0.3 on 2026-03-31 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_remove_rockcannon_slug_cy_remove_rockcannon_slug_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockCannonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='rock_cannons/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rock_cannon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forms.rockcannon')),
            ],
        ),
    ]
