# Generated by Django 6.0.3 on 2026-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rockcannonimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='has_channels',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('some', 'Some')], help_text='This is what is used in the book', max_length=10, null=True),
        ),
    ]
