# Generated by Django 6.0.3 on 2026-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_metadata_has_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='has_channels',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('some', 'Some')], help_text='These are the field values used in the Book The Rock Cannon of Gwynedd', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='is_on_private_land',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
