# Generated by Django 6.0.3 on 2026-04-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_metadata_has_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='os_easting',
        ),
        migrations.RemoveField(
            model_name='position',
            name='os_grid',
        ),
        migrations.RemoveField(
            model_name='position',
            name='os_northing',
        ),
        migrations.AddField(
            model_name='position',
            name='grid_ref',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
