# Generated by Django 6.0.3 on 2026-04-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_remove_position_os_easting_remove_position_os_grid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='grid_ref',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
