# Generated by Django 6.0.3 on 2026-05-05 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_position_grid_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rockcannonimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_text',
            field=models.TextField(help_text='This field will auto-translate into welsh when you save \n(Using Google Translate | Please check for correctness)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_text_cy',
            field=models.TextField(help_text='This field will auto-translate into welsh when you save \n(Using Google Translate | Please check for correctness)', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_text_en',
            field=models.TextField(help_text='This field will auto-translate into welsh when you save \n(Using Google Translate | Please check for correctness)', null=True),
        ),
    ]
