# Generated by Django 6.0.3 on 2026-05-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_gallerypage_homepage_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
