# Generated by Django 6.0.3 on 2026-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_homepage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_text_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
