# Generated by Django 6.0.3 on 2026-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_homepage_intro_text_cy_homepage_intro_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
