# Generated by Django 6.0.3 on 2026-05-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_homepage_content_paragraph_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_cy',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle_en',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_1_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_2_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_paragraph_2_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_1_cy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_1_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_2_cy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_subtitle_2_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title_cy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
