# Generated by Django 6.0.3 on 2026-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_galleryitem_delete_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text_cy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='title_cy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
